-- Isolated Past Papers grouped true/false exam system.
-- This intentionally does not reference public.quizzes, public.questions,
-- public.quiz_attempts, public.import_tf, or public.import_sba.

create table if not exists public.past_paper_sets (
  id uuid primary key default gen_random_uuid(),
  set_key text not null unique,
  title text not null,
  year_label text not null default '',
  paper_group_label text not null default 'Past Papers',
  topic_label text not null default '',
  description text,
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.past_paper_units (
  id uuid primary key default gen_random_uuid(),
  set_id uuid not null references public.past_paper_sets(id) on delete cascade,
  stem text not null,
  image_url text,
  explanation text,
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.past_paper_branches (
  id uuid primary key default gen_random_uuid(),
  unit_id uuid not null references public.past_paper_units(id) on delete cascade,
  branch_order integer not null,
  prompt text not null,
  correct_answer boolean not null,
  explanation text,
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint past_paper_branches_order_check check (branch_order between 1 and 5),
  constraint past_paper_branches_unit_order_unique unique (unit_id, branch_order)
);

create table if not exists public.past_paper_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  set_id uuid not null references public.past_paper_sets(id) on delete cascade,
  score integer not null default 0,
  total_marks integer not null default 0,
  correct_count integer not null default 0,
  wrong_count integer not null default 0,
  unanswered_count integer not null default 0,
  percentage integer not null default 0,
  completed_at timestamptz not null default now()
);

create table if not exists public.past_paper_attempt_answers (
  id bigint generated by default as identity primary key,
  attempt_id bigint not null references public.past_paper_attempts(id) on delete cascade,
  unit_id uuid not null references public.past_paper_units(id) on delete cascade,
  branch_id uuid not null references public.past_paper_branches(id) on delete cascade,
  user_answer boolean,
  correct_answer boolean not null,
  is_correct boolean not null default false,
  points integer not null default 0,
  answered_at timestamptz not null default now(),
  constraint past_paper_attempt_answers_unique unique (attempt_id, branch_id)
);

create table if not exists public.import_past_paper_units (
  id bigint generated by default as identity primary key,
  set_key text,
  set_title text not null,
  year_label text not null default '',
  paper_group_label text not null default 'Past Papers',
  topic_label text not null default '',
  unit_order integer,
  stem text not null,
  branch_1_prompt text not null,
  branch_1_answer text not null,
  branch_1_explanation text,
  branch_2_prompt text not null,
  branch_2_answer text not null,
  branch_2_explanation text,
  branch_3_prompt text not null,
  branch_3_answer text not null,
  branch_3_explanation text,
  branch_4_prompt text not null,
  branch_4_answer text not null,
  branch_4_explanation text,
  branch_5_prompt text not null,
  branch_5_answer text not null,
  branch_5_explanation text,
  source_note text,
  imported_at timestamptz not null default now(),
  processed_at timestamptz,
  error_message text
);

create index if not exists past_paper_sets_browse_idx
  on public.past_paper_sets (is_active, display_order, year_label, paper_group_label, topic_label, title);

create index if not exists past_paper_units_set_idx
  on public.past_paper_units (set_id, is_active, display_order);

create index if not exists past_paper_branches_unit_idx
  on public.past_paper_branches (unit_id, branch_order);

create index if not exists past_paper_attempts_user_set_idx
  on public.past_paper_attempts (user_id, set_id, completed_at desc);

create or replace function public.normalize_past_paper_answer(p_answer text)
returns boolean
language plpgsql
immutable
set search_path to 'public'
as $$
declare
  v_answer text := lower(trim(coalesce(p_answer, '')));
begin
  if v_answer in ('t', 'true', 'yes', 'y', '1') then
    return true;
  end if;

  if v_answer in ('f', 'false', 'no', 'n', '0') then
    return false;
  end if;

  raise exception 'Invalid past paper answer: %. Use true/false or T/F.', p_answer;
end;
$$;

create or replace function public.set_past_paper_updated_at()
returns trigger
language plpgsql
set search_path to 'public'
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_past_paper_sets_updated_at on public.past_paper_sets;
create trigger set_past_paper_sets_updated_at
before update on public.past_paper_sets
for each row execute function public.set_past_paper_updated_at();

drop trigger if exists set_past_paper_units_updated_at on public.past_paper_units;
create trigger set_past_paper_units_updated_at
before update on public.past_paper_units
for each row execute function public.set_past_paper_updated_at();

drop trigger if exists set_past_paper_branches_updated_at on public.past_paper_branches;
create trigger set_past_paper_branches_updated_at
before update on public.past_paper_branches
for each row execute function public.set_past_paper_updated_at();

create or replace function public.admin_import_past_paper_units()
returns integer
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_row public.import_past_paper_units%rowtype;
  v_set_id uuid;
  v_unit_id uuid;
  v_set_key text;
  v_imported integer := 0;
begin
  perform public.require_current_user_admin();

  for v_row in
    select *
    from public.import_past_paper_units
    where processed_at is null
    order by id
  loop
    begin
      v_set_key := nullif(trim(coalesce(v_row.set_key, '')), '');
      if v_set_key is null then
        v_set_key := md5(
          concat_ws(
            '|||',
            v_row.year_label,
            v_row.paper_group_label,
            v_row.topic_label,
            v_row.set_title
          )
        );
      end if;

      insert into public.past_paper_sets (
        set_key,
        title,
        year_label,
        paper_group_label,
        topic_label
      )
      values (
        v_set_key,
        trim(v_row.set_title),
        trim(coalesce(v_row.year_label, '')),
        trim(coalesce(v_row.paper_group_label, 'Past Papers')),
        trim(coalesce(v_row.topic_label, ''))
      )
      on conflict (set_key)
      do update set
        title = excluded.title,
        year_label = excluded.year_label,
        paper_group_label = excluded.paper_group_label,
        topic_label = excluded.topic_label
      returning id into v_set_id;

      insert into public.past_paper_units (
        set_id,
        stem,
        display_order
      )
      values (
        v_set_id,
        trim(v_row.stem),
        coalesce(v_row.unit_order, v_row.id::integer)
      )
      returning id into v_unit_id;

      insert into public.past_paper_branches (
        unit_id,
        branch_order,
        prompt,
        correct_answer,
        explanation
      )
      values
        (v_unit_id, 1, trim(v_row.branch_1_prompt), public.normalize_past_paper_answer(v_row.branch_1_answer), nullif(trim(coalesce(v_row.branch_1_explanation, '')), '')),
        (v_unit_id, 2, trim(v_row.branch_2_prompt), public.normalize_past_paper_answer(v_row.branch_2_answer), nullif(trim(coalesce(v_row.branch_2_explanation, '')), '')),
        (v_unit_id, 3, trim(v_row.branch_3_prompt), public.normalize_past_paper_answer(v_row.branch_3_answer), nullif(trim(coalesce(v_row.branch_3_explanation, '')), '')),
        (v_unit_id, 4, trim(v_row.branch_4_prompt), public.normalize_past_paper_answer(v_row.branch_4_answer), nullif(trim(coalesce(v_row.branch_4_explanation, '')), '')),
        (v_unit_id, 5, trim(v_row.branch_5_prompt), public.normalize_past_paper_answer(v_row.branch_5_answer), nullif(trim(coalesce(v_row.branch_5_explanation, '')), ''));

      update public.import_past_paper_units
      set processed_at = now(),
          error_message = null
      where id = v_row.id;

      v_imported := v_imported + 1;
    exception
      when others then
        update public.import_past_paper_units
        set error_message = sqlerrm
        where id = v_row.id;
    end;
  end loop;

  return v_imported;
end;
$$;

create or replace function public.app_past_paper_catalog()
returns table (
  set_id uuid,
  title text,
  year_label text,
  paper_group_label text,
  topic_label text,
  unit_count integer,
  total_marks integer,
  attempt_count integer,
  best_percentage integer,
  latest_percentage integer
)
language sql
stable
security definer
set search_path to 'public'
as $$
  with guard as (
    select public.app_require_active_access() as ok
  ),
  unit_counts as (
    select
      ns.id as set_id,
      count(distinct nu.id)::int as unit_count,
      count(nb.id)::int as total_marks
    from public.past_paper_sets ns
    left join public.past_paper_units nu
      on nu.set_id = ns.id
     and nu.is_active
    left join public.past_paper_branches nb
      on nb.unit_id = nu.id
    group by ns.id
  ),
  attempts as (
    select
      set_id,
      count(*)::int as attempt_count,
      max(percentage)::int as best_percentage,
      (array_agg(percentage order by completed_at desc, id desc))[1]::int as latest_percentage
    from public.past_paper_attempts
    where user_id = auth.uid()
    group by set_id
  )
  select
    ns.id,
    ns.title,
    ns.year_label,
    ns.paper_group_label,
    ns.topic_label,
    coalesce(uc.unit_count, 0),
    coalesce(uc.total_marks, 0),
    coalesce(a.attempt_count, 0),
    coalesce(a.best_percentage, 0),
    coalesce(a.latest_percentage, 0)
  from guard
  cross join public.past_paper_sets ns
  left join unit_counts uc on uc.set_id = ns.id
  left join attempts a on a.set_id = ns.id
  where ns.is_active
  order by ns.display_order, ns.year_label, ns.paper_group_label, ns.topic_label, ns.title;
$$;

create or replace function public.app_past_paper_years()
returns table (
  year_label text,
  paper_group_label text,
  topic_count integer,
  exam_count integer,
  unit_count integer,
  total_marks integer,
  attempt_count integer,
  best_percentage integer
)
language sql
stable
security definer
set search_path to 'public'
as $$
  with catalog as (
    select *
    from public.app_past_paper_catalog()
  )
  select
    year_label,
    paper_group_label,
    count(distinct topic_label)::int as topic_count,
    count(distinct set_id)::int as exam_count,
    sum(unit_count)::int as unit_count,
    sum(total_marks)::int as total_marks,
    sum(attempt_count)::int as attempt_count,
    coalesce(max(nullif(best_percentage, 0)), 0)::int as best_percentage
  from catalog
  group by year_label, paper_group_label
  order by year_label, paper_group_label;
$$;

create or replace function public.app_past_paper_topics(
  p_year_label text,
  p_paper_group_label text default 'Past Papers'
)
returns table (
  year_label text,
  paper_group_label text,
  topic_label text,
  exam_count integer,
  unit_count integer,
  total_marks integer,
  attempt_count integer,
  best_percentage integer
)
language sql
stable
security definer
set search_path to 'public'
as $$
  with catalog as (
    select *
    from public.app_past_paper_catalog()
    where lower(trim(year_label)) = lower(trim(coalesce(p_year_label, '')))
      and lower(trim(paper_group_label)) = lower(trim(coalesce(p_paper_group_label, 'Past Papers')))
  )
  select
    year_label,
    paper_group_label,
    topic_label,
    count(distinct set_id)::int as exam_count,
    sum(unit_count)::int as unit_count,
    sum(total_marks)::int as total_marks,
    sum(attempt_count)::int as attempt_count,
    coalesce(max(nullif(best_percentage, 0)), 0)::int as best_percentage
  from catalog
  group by year_label, paper_group_label, topic_label
  order by topic_label;
$$;

create or replace function public.app_past_paper_exams(
  p_year_label text,
  p_topic_label text,
  p_paper_group_label text default 'Past Papers'
)
returns table (
  set_id uuid,
  title text,
  year_label text,
  paper_group_label text,
  topic_label text,
  unit_count integer,
  total_marks integer,
  attempt_count integer,
  best_percentage integer,
  latest_percentage integer
)
language sql
stable
security definer
set search_path to 'public'
as $$
  select
    set_id,
    title,
    year_label,
    paper_group_label,
    topic_label,
    unit_count,
    total_marks,
    attempt_count,
    best_percentage,
    latest_percentage
  from public.app_past_paper_catalog()
  where lower(trim(year_label)) = lower(trim(coalesce(p_year_label, '')))
    and lower(trim(topic_label)) = lower(trim(coalesce(p_topic_label, '')))
    and lower(trim(paper_group_label)) = lower(trim(coalesce(p_paper_group_label, 'Past Papers')))
  order by title;
$$;

create or replace function public.app_past_paper_units(p_set_id uuid)
returns table (
  unit_id uuid,
  stem text,
  image_url text,
  display_order integer,
  branches jsonb
)
language sql
stable
security definer
set search_path to 'public'
as $$
  with guard as (
    select public.app_require_active_access() as ok
  )
  select
    nu.id,
    nu.stem,
    nu.image_url,
    nu.display_order,
    jsonb_agg(
      jsonb_build_object(
        'branchId', nb.id,
        'order', nb.branch_order,
        'prompt', nb.prompt,
        'imageUrl', nb.image_url
      )
      order by nb.branch_order
    ) as branches
  from guard
  cross join public.past_paper_units nu
  join public.past_paper_sets ns
    on ns.id = nu.set_id
   and ns.is_active
  join public.past_paper_branches nb
    on nb.unit_id = nu.id
  where nu.set_id = p_set_id
    and nu.is_active
  group by nu.id
  having count(nb.id) = 5
  order by nu.display_order, nu.id;
$$;

create or replace function public.app_submit_past_paper_attempt(
  p_set_id uuid,
  p_answers jsonb
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_attempt_id bigint;
  v_score integer := 0;
  v_total integer := 0;
  v_correct integer := 0;
  v_wrong integer := 0;
  v_unanswered integer := 0;
  v_branch record;
  v_answer_text text;
  v_user_answer boolean;
  v_is_correct boolean;
begin
  perform public.app_require_active_access();

  if p_set_id is null then
    raise exception 'Set id is required.';
  end if;

  if not exists (
    select 1
    from public.past_paper_sets
    where id = p_set_id
      and is_active
  ) then
    raise exception 'Past paper set not found.';
  end if;

  insert into public.past_paper_attempts (user_id, set_id)
  values (auth.uid(), p_set_id)
  returning id into v_attempt_id;

  for v_branch in
    select
      nu.id as unit_id,
      nb.id as branch_id,
      nb.correct_answer
    from public.past_paper_units nu
    join public.past_paper_branches nb on nb.unit_id = nu.id
    where nu.set_id = p_set_id
      and nu.is_active
    order by nu.display_order, nb.branch_order
  loop
    v_total := v_total + 1;
    v_answer_text := p_answers ->> v_branch.branch_id::text;

    if v_answer_text is null then
      v_user_answer := null;
      v_is_correct := false;
      v_unanswered := v_unanswered + 1;
    else
      v_user_answer := public.normalize_past_paper_answer(v_answer_text);
      v_is_correct := v_user_answer = v_branch.correct_answer;
      if v_is_correct then
        v_score := v_score + 1;
        v_correct := v_correct + 1;
      else
        v_wrong := v_wrong + 1;
      end if;
    end if;

    insert into public.past_paper_attempt_answers (
      attempt_id,
      unit_id,
      branch_id,
      user_answer,
      correct_answer,
      is_correct,
      points
    )
    values (
      v_attempt_id,
      v_branch.unit_id,
      v_branch.branch_id,
      v_user_answer,
      v_branch.correct_answer,
      v_is_correct,
      case when v_is_correct then 1 else 0 end
    );
  end loop;

  update public.past_paper_attempts
  set
    score = v_score,
    total_marks = v_total,
    correct_count = v_correct,
    wrong_count = v_wrong,
    unanswered_count = v_unanswered,
    percentage = case when v_total > 0 then round((v_score::numeric / v_total::numeric) * 100)::int else 0 end
  where id = v_attempt_id;

  return jsonb_build_object(
    'attemptId', v_attempt_id,
    'score', v_score,
    'totalMarks', v_total,
    'correct', v_correct,
    'wrong', v_wrong,
    'unanswered', v_unanswered,
    'percentage', case when v_total > 0 then round((v_score::numeric / v_total::numeric) * 100)::int else 0 end
  );
end;
$$;

create or replace function public.app_past_paper_attempt_review(p_attempt_id bigint)
returns jsonb
language sql
stable
security definer
set search_path to 'public'
as $$
  with guard as (
    select public.app_require_active_access() as ok
  ),
  attempt as (
    select *
    from public.past_paper_attempts
    where id = p_attempt_id
      and user_id = auth.uid()
  ),
  units as (
    select
      nu.id as unit_id,
      nu.stem,
      nu.image_url,
      nu.display_order,
      jsonb_agg(
        jsonb_build_object(
          'branchId', nb.id,
          'order', nb.branch_order,
          'prompt', nb.prompt,
          'userAnswer', naa.user_answer,
          'correctAnswer', naa.correct_answer,
          'isCorrect', naa.is_correct,
          'points', naa.points,
          'explanation', nb.explanation
        )
        order by nb.branch_order
      ) as branches
    from attempt a
    join public.past_paper_units nu on nu.set_id = a.set_id
    join public.past_paper_branches nb on nb.unit_id = nu.id
    left join public.past_paper_attempt_answers naa
      on naa.attempt_id = a.id
     and naa.branch_id = nb.id
    group by nu.id
  )
  select jsonb_build_object(
    'attempt', jsonb_build_object(
      'attemptId', a.id,
      'setId', a.set_id,
      'score', a.score,
      'totalMarks', a.total_marks,
      'correct', a.correct_count,
      'wrong', a.wrong_count,
      'unanswered', a.unanswered_count,
      'percentage', a.percentage,
      'completedAt', a.completed_at
    ),
    'units', coalesce(
      jsonb_agg(
        jsonb_build_object(
          'unitId', u.unit_id,
          'stem', u.stem,
          'imageUrl', u.image_url,
          'branches', u.branches
        )
        order by u.display_order, u.unit_id
      ),
      '[]'::jsonb
    )
  )
  from guard
  cross join attempt a
  left join units u on true
  group by a.id, a.set_id, a.score, a.total_marks, a.correct_count, a.wrong_count, a.unanswered_count, a.percentage, a.completed_at;
$$;

alter table public.past_paper_sets enable row level security;
alter table public.past_paper_units enable row level security;
alter table public.past_paper_branches enable row level security;
alter table public.past_paper_attempts enable row level security;
alter table public.past_paper_attempt_answers enable row level security;
alter table public.import_past_paper_units enable row level security;

drop policy if exists past_paper_sets_read_active_access on public.past_paper_sets;
create policy past_paper_sets_read_active_access
on public.past_paper_sets for select to authenticated
using (is_active and public.app_current_user_has_access());

drop policy if exists past_paper_units_read_active_access on public.past_paper_units;
create policy past_paper_units_read_active_access
on public.past_paper_units for select to authenticated
using (is_active and public.app_current_user_has_access());

-- No authenticated direct-read policy for past_paper_branches.
-- Branch rows include correct_answer, so learner reads must go through RPCs
-- that omit answers before submission and include answers only in reviews.

drop policy if exists past_paper_attempts_select_own_active_access on public.past_paper_attempts;
create policy past_paper_attempts_select_own_active_access
on public.past_paper_attempts for select to authenticated
using (user_id = auth.uid() and public.app_current_user_has_access());

drop policy if exists past_paper_attempt_answers_select_own_active_access on public.past_paper_attempt_answers;
create policy past_paper_attempt_answers_select_own_active_access
on public.past_paper_attempt_answers for select to authenticated
using (
  exists (
    select 1
    from public.past_paper_attempts na
    where na.id = attempt_id
      and na.user_id = auth.uid()
  )
  and public.app_current_user_has_access()
);

grant select on public.past_paper_sets to authenticated;
grant select on public.past_paper_units to authenticated;
grant select on public.past_paper_attempts to authenticated;
grant select on public.past_paper_attempt_answers to authenticated;

grant all on public.past_paper_sets to service_role;
grant all on public.past_paper_units to service_role;
grant all on public.past_paper_branches to service_role;
grant all on public.past_paper_attempts to service_role;
grant all on public.past_paper_attempt_answers to service_role;
grant all on public.import_past_paper_units to service_role;

revoke execute on function public.normalize_past_paper_answer(text) from public, anon;
revoke execute on function public.set_past_paper_updated_at() from public, anon;
revoke execute on function public.app_past_paper_catalog() from public, anon;
revoke execute on function public.app_past_paper_years() from public, anon;
revoke execute on function public.app_past_paper_topics(text, text) from public, anon;
revoke execute on function public.app_past_paper_exams(text, text, text) from public, anon;
revoke execute on function public.app_past_paper_units(uuid) from public, anon;
revoke execute on function public.app_submit_past_paper_attempt(uuid, jsonb) from public, anon;
revoke execute on function public.app_past_paper_attempt_review(bigint) from public, anon;
revoke execute on function public.admin_import_past_paper_units() from public, anon;

grant execute on function public.app_past_paper_catalog() to authenticated, service_role;
grant execute on function public.app_past_paper_years() to authenticated, service_role;
grant execute on function public.app_past_paper_topics(text, text) to authenticated, service_role;
grant execute on function public.app_past_paper_exams(text, text, text) to authenticated, service_role;
grant execute on function public.app_past_paper_units(uuid) to authenticated, service_role;
grant execute on function public.app_submit_past_paper_attempt(uuid, jsonb) to authenticated, service_role;
grant execute on function public.app_past_paper_attempt_review(bigint) to authenticated, service_role;
grant execute on function public.admin_import_past_paper_units() to authenticated, service_role;

