-- Past Papers variable branch support.
-- Allows each imported Past Paper unit to contain 1 to 5 contiguous branches.
-- Run this after the original Past Papers schema and friendly staging SQL.
-- SQL editor/database superuser roles may run this directly.
-- App-authenticated execution still goes through require_current_user_admin().

create table if not exists public.import_past_papers (
  id bigint generated by default as identity primary key,
  "Title" text not null,
  "Year" text not null default '',
  "Module" text not null default '',
  "Question Number" integer,
  "Stem" text not null,
  "Statement 1" text not null,
  "Answer 1" text not null,
  "Explanation 1" text,
  "Statement 2" text,
  "Answer 2" text,
  "Explanation 2" text,
  "Statement 3" text,
  "Answer 3" text,
  "Explanation 3" text,
  "Statement 4" text,
  "Answer 4" text,
  "Explanation 4" text,
  "Statement 5" text,
  "Answer 5" text,
  "Explanation 5" text,
  imported_at timestamptz not null default now(),
  processed_at timestamptz,
  error_message text
);

alter table public.import_past_papers
  alter column "Statement 2" drop not null,
  alter column "Answer 2" drop not null,
  alter column "Statement 3" drop not null,
  alter column "Answer 3" drop not null,
  alter column "Statement 4" drop not null,
  alter column "Answer 4" drop not null,
  alter column "Statement 5" drop not null,
  alter column "Answer 5" drop not null;

create or replace function public.import_past_papers()
returns integer
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_row public.import_past_papers%rowtype;
  v_set_id uuid;
  v_unit_id uuid;
  v_set_key text;
  v_imported integer := 0;
  v_prompts text[];
  v_answers text[];
  v_explanations text[];
  v_prompt text;
  v_answer text;
  v_explanation text;
  v_branch_count integer;
  v_gap_started boolean;
  i integer;
begin
  if current_user not in ('postgres', 'supabase_admin', 'service_role')
     and session_user not in ('postgres', 'supabase_admin', 'service_role') then
    perform public.require_current_user_admin();
  end if;

  for v_row in
    select *
    from public.import_past_papers
    where processed_at is null
    order by id
  loop
    begin
      v_prompts := array[
        v_row."Statement 1",
        v_row."Statement 2",
        v_row."Statement 3",
        v_row."Statement 4",
        v_row."Statement 5"
      ];
      v_answers := array[
        v_row."Answer 1",
        v_row."Answer 2",
        v_row."Answer 3",
        v_row."Answer 4",
        v_row."Answer 5"
      ];
      v_explanations := array[
        v_row."Explanation 1",
        v_row."Explanation 2",
        v_row."Explanation 3",
        v_row."Explanation 4",
        v_row."Explanation 5"
      ];
      v_branch_count := 0;
      v_gap_started := false;

      for i in 1..5 loop
        v_prompt := nullif(trim(coalesce(v_prompts[i], '')), '');
        v_answer := nullif(trim(coalesce(v_answers[i], '')), '');
        v_explanation := nullif(trim(coalesce(v_explanations[i], '')), '');

        if v_prompt is null and v_answer is null and v_explanation is null then
          v_gap_started := true;
          continue;
        end if;

        if v_gap_started then
          raise exception 'Branch % is filled after an empty earlier branch. Fill statements in order from 1 to 5.', i;
        end if;

        if v_prompt is null then
          raise exception 'Statement % is required when Answer % or Explanation % is provided.', i, i, i;
        end if;

        if v_answer is null then
          raise exception 'Answer % is required when Statement % is provided.', i, i;
        end if;

        perform public.normalize_past_paper_answer(v_answer);
        v_branch_count := v_branch_count + 1;
      end loop;

      if v_branch_count < 1 then
        raise exception 'At least Statement 1 and Answer 1 are required.';
      end if;

      v_set_key := md5(
        concat_ws(
          '|||',
          trim(coalesce(v_row."Year", '')),
          'Past Papers',
          trim(coalesce(v_row."Module", '')),
          trim(v_row."Title")
        )
      );

      insert into public.past_paper_sets (
        set_key,
        title,
        year_label,
        paper_group_label,
        topic_label
      )
      values (
        v_set_key,
        trim(v_row."Title"),
        trim(coalesce(v_row."Year", '')),
        'Past Papers',
        trim(coalesce(v_row."Module", ''))
      )
      on conflict (set_key)
      do update set
        title = excluded.title,
        year_label = excluded.year_label,
        paper_group_label = excluded.paper_group_label,
        topic_label = excluded.topic_label
      returning id into v_set_id;

      insert into public.past_paper_units (
        set_id,
        stem,
        display_order
      )
      values (
        v_set_id,
        trim(v_row."Stem"),
        coalesce(v_row."Question Number", v_row.id::integer)
      )
      returning id into v_unit_id;

      for i in 1..v_branch_count loop
        v_prompt := trim(v_prompts[i]);
        v_answer := trim(v_answers[i]);
        v_explanation := nullif(trim(coalesce(v_explanations[i], '')), '');

        insert into public.past_paper_branches (
          unit_id,
          branch_order,
          prompt,
          correct_answer,
          explanation
        )
        values (
          v_unit_id,
          i,
          v_prompt,
          public.normalize_past_paper_answer(v_answer),
          v_explanation
        );
      end loop;

      update public.import_past_papers
      set processed_at = now(),
          error_message = null
      where id = v_row.id;

      v_imported := v_imported + 1;
    exception
      when others then
        update public.import_past_papers
        set error_message = sqlerrm
        where id = v_row.id;
    end;
  end loop;

  return v_imported;
end;
$$;

create or replace function public.app_past_paper_units(p_set_id uuid)
returns table (
  unit_id uuid,
  stem text,
  image_url text,
  display_order integer,
  branches jsonb
)
language sql
stable
security definer
set search_path to 'public'
as $$
  with guard as (
    select public.app_require_active_access() as ok
  )
  select
    nu.id,
    nu.stem,
    nu.image_url,
    nu.display_order,
    jsonb_agg(
      jsonb_build_object(
        'branchId', nb.id,
        'order', nb.branch_order,
        'prompt', nb.prompt,
        'imageUrl', nb.image_url
      )
      order by nb.branch_order
    ) as branches
  from guard
  cross join public.past_paper_units nu
  join public.past_paper_sets ns
    on ns.id = nu.set_id
   and ns.is_active
  join public.past_paper_branches nb
    on nb.unit_id = nu.id
  where nu.set_id = p_set_id
    and nu.is_active
  group by nu.id
  having count(nb.id) between 1 and 5
  order by nu.display_order, nu.id;
$$;

alter table public.import_past_papers enable row level security;

grant all on public.import_past_papers to service_role;

revoke execute on function public.import_past_papers() from public, anon, authenticated;
revoke execute on function public.app_past_paper_units(uuid) from public, anon;

grant execute on function public.import_past_papers() to authenticated, service_role;
grant execute on function public.app_past_paper_units(uuid) to authenticated, service_role;
