import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { transform } from "lightningcss";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(scriptDirectory, "..");
const publicDirectory = path.join(projectRoot, "public");
const manifestPath = path.join(publicDirectory, "style.css");
const outputPath = path.join(publicDirectory, "style.bundle.css");

const manifest = await readFile(manifestPath, "utf8");
const stylesheetUrls = Array.from(
  manifest.matchAll(/^@import\s+url\(["'](\/styles\/[^"']+\.css)["']\);\s*$/gm),
  (match) => match[1]
);

if (!stylesheetUrls.length) {
  throw new Error(`No local stylesheet imports found in ${manifestPath}.`);
}

const sections = await Promise.all(
  stylesheetUrls.map(async (stylesheetUrl) => {
    const sourcePath = path.join(
      publicDirectory,
      ...stylesheetUrl.replace(/^\/+/, "").split("/")
    );
    const source = await readFile(sourcePath, "utf8");
    return `/* Source: ${stylesheetUrl} */\n${source.trimEnd()}`;
  })
);

const sourceBundle = [
  "/* Generated by scripts/build-app-css.mjs. Edit the source files listed in public/style.css. */",
  ...sections,
  "",
].join("\n\n");
const bundle = transform({
  code: Buffer.from(sourceBundle),
  filename: outputPath,
  minify: true,
}).code;

await writeFile(outputPath, bundle);
console.log(
  `Built ${path.relative(projectRoot, outputPath)} from ${stylesheetUrls.length} stylesheets.`
);
